version: '3.7'

services:
  nginx:
    image: nginx:1.21.5-alpine
    volumes:
      - ./docker/etc_nginx:/etc/nginx:ro
      - ./docker/usr_share_nginx:/usr/share/nginx
    ports:
      - "80:80"

  samba:
    image: dperson/samba:amd64
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${SHARED_PATH}:/mnt
    command: '-s "Storage;/mnt;yes;no;no;${USER_NAME}" -u "${USER_NAME};${USER_PASS}" -p'
    # -s "<name;/path>[;browse;readonly;guest;users;admins;writelist;comment]"

