---
- name: Start docker-compose
  hosts: GREEN_SERVER
  become: yes

  tasks:
    - name: Run 'docker-compose up'
      community.docker.docker_compose:
        project_src: /opt/green
        state: present
      register: output

    - ansible.builtin.debug:
        var: output