---
- name: Clone repository
  hosts: GREEN_SERVER
  become: yes

  tasks:
    - name: Git clone of a single branch
      ansible.builtin.git:
        repo: https://github.com/MaxBogach/green.git
        dest: /opt/green
        single_branch: yes
        version: master